#pragma once

// #define EE_HANDS
#define MASTER_RIGHT
#define SPLIT_USB_TIMEOUT 2000
#define SPLIT_LAYER_STATE_ENABLE

#define MOUSEKEY_INTERVAL 6
#define MOUSEKEY_MAX_SPEED 7

// #define ENABLE_RGB_MATRIX_RAINDROPS
// #define RGB_MATRIX_TIMEOUT 900000